declare class BiliApi {
    biliConfigData: any;
    USER_AGENT: string;
    constructor();
    static BILIBILI_USER_AGENT: string;
    initialize(): Promise<void>;
    initUserAgent(): Promise<void>;
    get BILIBIL_API(): {
        biliDynamicInfoList: string;
        biliUpFollowFans: string;
        biliSpaceUserInfo: string;
        biliSpaceUserInfoWbi: string;
        biliSearchUp: string;
        biliSearchUpWbi: string;
        biliLiveStatus: string;
        biliCard: string;
        biliStat: string;
        biliLiveUserInfo: string;
        biliOpusDetail: string;
    };
    get BILIBILI_HEADERS(): {
        Accept: string;
        'Accept-Language': string;
        Connection: string;
        'Accept-Encoding': string;
        Cookie: string;
        pragma: string;
        'Cache-control': string;
        DNT: string;
        'Sec-GPC': string;
        'sec-ch-ua-platform': string;
        'sec-ch-ua-mobile': string;
        'Sec-Fetch-Dest': string;
        'Sec-Fetch-Mode': string;
        'Sec-Fetch-Site': string;
        'Sec-Fetch-User': string;
        Priority: string;
        TE: string;
        'User-Agent': string;
    };
    get BIlIBILI_LOGIN_HEADERS(): {
        Accept: string;
        'Accept-Language': string;
        'Accept-Encoding': string;
        DNT: string;
        'Sec-GPC': string;
        'Upgrade-Insecure-Requests': string;
        'Sec-Fetch-Dest': string;
        'Sec-Fetch-Mode': string;
        'Sec-Fetch-Site': string;
        'Sec-Fetch-User': string;
        TE: string;
    };
    get BILIBILI_ARTICLE_HEADERS(): {
        Accept: string;
        'Accept-Language': string;
        'Accept-Encoding': string;
        'Content-type': string;
        Cookie: string;
        pragma: string;
        'Cache-control': string;
        DNT: string;
        'Sec-GPC': string;
        'sec-ch-ua-mobile': string;
        'Sec-Fetch-Dest': string;
        'Sec-Fetch-Mode': string;
        'Sec-Fetch-Site': string;
        'Sec-Fetch-User': string;
        TE: string;
        'Upgrade-Insecure-Requests': string;
        'User-Agent': string;
    };
    get BILIBILI_DYNAMIC_SPACE_HEADERS(): {
        Accept: string;
        'Accept-Encoding': string;
        'Accept-Language': string;
        Connection: string;
        Priority: string;
        'Sec-Fetch-Dest': string;
        'Sec-Fetch-Mode': string;
        'Sec-Fetch-Site': string;
        'Sec-Fetch-User': string;
        'Sec-GPC': string;
        'Upgrade-Insecure-Requests': string;
        'User-Agent': string;
    };
}
declare const _default: BiliApi;
export default _default;
