# 微博推送，1 开启 0 关闭，保留添加的相关数据，但是不再推送
pushStatus: 1

# 检测微博动态的冷却时间 CD，Cron表达式，作用域共6位，具体方法浏览器搜索 “node-schedule cron表达式”，
# 示例：
# "*/15  * * * *" #每15min检测一次
# "*/31  * * * *" #每31min检测一次
# "0 5,35 * * * *" #每小时固定第5分0秒、第35分0秒检测一次，共2次/h
# "0 5,35,51 * * * *" #每小时固定第5分0秒、第35分0秒、第51分0秒检测一次，共3次/h
# ❀动态发布通常习惯整点发布，触发检测时比发布时间点稍晚几分钟即可，基本可以命中。
# ❀请勿设置周期过短比如小于10分钟，以免触发访问限制。
checkDynamicCD: '*/23  * * * *'

# 请求头 User-Agent 列表。请根据需要自行添加或修改。
# 可设置多个请求头，每次重启后会随机选择一个。获取方法请浏览器自行搜索。
userAgentList:
  - Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/132.0.0.0 Safari/537.36
  #- Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:134.0) Gecko/20100101 Firefox/134.0
  #- Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/132.0.0.0 Safari/537.36 Edg/132.0.0.0

# 筛选何时发布的动态，单位为秒，默认7200秒即2小时，即以当前时间为基准，筛选过去2小时内发布的动态，并推送。
# 取值范围：3600-36000秒，即过去的1-10h。应大于checkDynamicCD的周期。
dynamicTimeRange: 7200

# 全部订阅的转发动态是否推送： 默认 1 - 开启推送， 0 - 关闭推送。
# 如果仅仅需要关闭单个订阅的转发动态推送，使用分类订阅指令不包含 转发 分类即可，无需修改此配置。
pushTransmit: 1

# 推送动态时，限制发送多少张图片
pushPicCountLimit: 9

# 推送文字和图文动态时，限制字数是多少
pushContentLenLimit: 1000

# 推送文字和图文动态时，限制多少行文本
pushContentLineLimit: 100

# 是否展示定时任务的日志，0 不显示 1 显示
pushTaskLog: 1

# 白名单关键词，命中即推送，不在白名单则不推送。
# 白名单与黑名单共同起作用，即命中白名单但不命中黑名单即推送，不在白名单或命中黑名单则不推送。
# 白名单为空则不启用白名单功能。
# 配置示例：
# whiteWordslist:
#   - 白名单关键词1
#   - 白名单关键词2
whiteWordslist:

# 包含关键词不推送
banWords:
  - 关键词1
  - 关键词2

# 设置微博动态消息模式 0 文字模式 1 图片模式
pushMsgMode: 1

# 动态过长或条图片数过多时是否以转发形式发送动态，默认 1 开启，0 关闭。
forwardSendDynamic: 1
maxPicsForSingleMsg: 2 # 阈值＞2张图片时
maxTextLengthForSingleMsg: 300 # 或阈值＞300字时

# 文字模式时，文字消息与图片附件是否合并在一起发送，默认 1 合并，0 不合并。
# 如果合并时图片过多导致发送失败，可设置为 0 单独发送图片。
mergeTextPic: 1

# 是否启用九宫格样式：默认 1 启用，0 不启用。
# 此为最高优先级，九宫格为动态模式，特定大小/长宽比的图片资源将会动态启用九宫格/四宫格/无宫格样式。
boxGrid: 1

# 微博动态卡片分片截图模式：默认 1 启用 0 不启用。
# 启用，将会推送每条动态的全部内容；不启用，动态内容过长时候将只推送noSplitHeight长度的动态卡片，需关闭宫格模式。
isSplit: 1

# 动态卡片非分片模式下的截图高度，默认7500px（仅填数字，无需填入单位），请勿设置过大或过小。关闭分片截图时生效。
noSplitHeight: 7500

# 动态卡片分页截图高度，默认8000px（仅填数字，无需填入单位），请勿设置过大或过小。启用分片截图时生效。
splitHeight: 8000
